### ISSUE TITLE
scoreMatrix and scoreMatrixBin should have "noCovNA" argument when dealing with bigwig files

### ISSUE THREAD

**Issue by al2na** [BIMSBbioinfo/genomation#113]
Currently, if bigWig files have methylation info, scoreMatrix function will read the uncovered bases as 0 score, meaning 0% methylation, which is wrong. They should have NA values not 0. Currently, this can only be achieved reading the bigWig file as GRanges object (using rtracklayer::import.bw) and using the scoreMatrix on GRanges with noCovNA=TRUE.

**Comment by katwre** [comment]
it's fixed here https://github.com/BIMSBbioinfo/genomation/commit/5d0b449193e99233ef7556efc1292fe85ae334c0
