### ISSUE TITLE
plotMeta doesn't work when dispersion=NULL and smoothfun=stats::lowess

### ISSUE THREAD

**Issue by al2na** [BIMSBbioinfo/genomation#116]
I get the following error:
Error in if (dispersion %in% disp.args) { : argument is of length zero

this should work when dispersion is NULL

**Comment by katwre** [comment]
it's done https://github.com/BIMSBbioinfo/genomation/commit/593ec3eaca87e03395cb1119e0a3639c55c7f99a

**Comment by katwre** [comment]
bug fixed https://github.com/BIMSBbioinfo/genomation/pull/117

**Comment by katwre** [comment]
it can be closed
