### ISSUE TITLE
intersectScoreMatrixList does not work when bin.num=1

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/genomation#135]
when bin.num = 1 rownames does not exist and intersectScoreMatrixList function does not work

**Comment by al2na** [comment]
is this still an issue ?

**Comment by frenkiboy** [comment]
I have to check - I did some improvements on genomation, but they are on my dev profile, I didn't push them - I have to check how much my dev profile differs from the master on bimsb
