### ISSUE TITLE
RPM should be computed based on mapped reads only.

### ISSUE THREAD

**Issue by FedericoComoglio** [BIMSBbioinfo/genomation#137]
I realized RPM values are computed based on all reads in a BAM file, as returned by 

```
countBam(BamFile(target))$records
```

in the readBam function:

```
if(rpm){
    message('Normalizing to rpm ...')
    if(is.null(library.size)){
      total = 1e6/sum(countBam(BamFile(target))$records)
    }else{
      total = 1e6/library.size
    }
    covs = covs * total
  }
```

This can lead to misleading results if the BAM files are not filtered to retain mapped reads only. However, the issue can be easily fixed by providing a param argument to the countBam function, such as:

```
ScanBamParam( flag = scanBamFlag(isUnmappedQuery=FALSE) )
```

Hope this helps.

**Comment by al2na** [comment]
@katwre could you make this change when you have time?

**Comment by FedericoComoglio** [comment]
Thank you for taking care of this issue. I would also suggest to add a line in the NEWS file/log to inform users about it.

**Comment by al2na** [comment]
Yes, we usually do that when we change something.

**Comment by FedericoComoglio** [comment]
Great. Thank you.

**Comment by katwre** [comment]
@al2na yes, sure

**Comment by al2na** [comment]
https://github.com/BIMSBbioinfo/genomation/pull/139
