### ISSUE TITLE
Option to add control sample (e.g. IgG ChIP/input DNA) in ScoreMatrix and ScoreMatrixList

### ISSUE THREAD

**Issue by FedericoComoglio** [BIMSBbioinfo/genomation#138]
The current implementation of ScoreMatrix does not allow to normalize ChIP-seq signals with respect to a commonly used IgG or input DNA control. I currently compute enrichment over control using custom functions, and then replace scores in the .@Data slot of a ScoreMatrix/ScoreMatrixList object prior to plotting.

It would be very nice to have the option to compute enrichments directly. A possible way to introduce this feature, is to provide a target object of two different classes: a vector for current behaviour, a matrix (e.g. a design matrix) specifying the sample/control pairs in the experimental design for computation of enrichments.

**Comment by al2na** [comment]
if you have two ScoreMatrix objects from IP and control (both normalized to sequencing depth and have same dimensions), calculating the enrichment is as follows. 

```
log2((IP.sm+1)/(ctrl.sm+1))

```
I'm not sure this requires an additional function.

**Comment by FedericoComoglio** [comment]
I understand, but if you have several (e.g. >100) such instances, each with their own control sample or with a subset of sample ChIPs sharing the same control, it would be nice to accommodate for the experimental design when generating the object in first place. Of course I understand this might not be a top priority for future devel.

**Comment by al2na** [comment]
we will do this in time, we have also internal code doing something
similar. I'm not sure if it will be a new function or additional argument
to ScoreMatrix

**Comment by FedericoComoglio** [comment]
@al2na Thank you for considering this option. I think an additional argument to ScoreMatrix, or as I said, a differentiation of the class of target could work well. Also, this would allow you to add pseudocounts to the window/bin counts prior to correcting for the offsets.

**Comment by frenkiboy** [comment]
We can maybe add the math operators on ScoreMatrixList? 
In this way you can have one list with chips, one list with cont, and just make the ratio
