### ISSUE TITLE
scoreMatrixList drops names after subsetting

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/genomation#141]
After I subset the scoreMatrixList; names(sml) returns NULL, while
names(sml) = 1:10 gives

 class 'ScoreMatrixList' has no 'names' slot; assigning a names attribute will create an invalid object

Have no idea what is happening

**Comment by al2na** [comment]
this could help here but it also comes with its own problems
http://stackoverflow.com/questions/23788082/subclassing-s4-class-that-contains-a-list-with-names-access-by-name

**Comment by al2na** [comment]
or this works, more of a hack:
`setMethod("[",signature(x="ScoreMatrixList", i = "ANY"), 
          function(x,i){
            tmp=sml@.Data[i]
            names(tmp)=names(x)[i]
            ScoreMatrixList( tmp)
            #initialize(x, x@.Data[i], names=names(x)[i])
            
          }
)
`
