### ISSUE TITLE
readNarrowPeak zero-base

### ISSUE THREAD

**Issue by changebio** [BIMSBbioinfo/genomation#144]
hi, have you consider that the narrowPeak, the output of MAC2, is a **zero-base** bed6+4 file  when you use readNarrowPeak to read it? Because I used the readNarrowPeak function to read a narrowPeak file, the coordinate of the GRanges seemed to be zero-base, which should be one-base.

**Comment by al2na** [comment]
You can use the following line to read narrowPeak files. It is almost the same code in readNarrowPeak() minus the zero.based=TRUE argument.

```
readGeneric(file,
                  strand=6,
                  meta.cols=list(name=4,
                                 score=5,
                                 signalValue=7,
                                 pvalue=8,
                                 qvalue=9,
                                 peak=10),
                  header=FALSE,
                  skip=1,
                  zero.based=TRUE)
```

**Comment by katwre** [comment]
@al2na @frenkiboy  adding to readNarrowPeak argument zero.based (with default zero.based=TRUE) would solve this issue? I can see on UCSC website ( genome.ucsc.edu/FAQ/FAQformat.html#format12 ) and macs ( github.com/taoliu/MACS ) that there narrowpeak and broadpeak formats are 0-based.
