### ISSUE TITLE
scoreMatrixBin with GRangesList input must sort exons internally, in addition there is a bug with GRangesList input

### ISSUE THREAD

**Issue by al2na** [BIMSBbioinfo/genomation#146]
currently, scoreMatrixBin can take GRangesList as input and can create a binned scoreMatrix by stitching exons coordinates. the function should sort the exon coordinates to the expected order, which is exon rank within respective strand, where the 1st exon in minus strand is the last exon in the coordinate system. **In addition, there is a bug where the coverage profiles on the - strand is not properly reversed when strand.aware is TRUE.**

**Comment by al2na** [comment]
@frenkiboy could you fix this? details are at @katwre and @borauyar

**Comment by al2na** [comment]
is this fixed? please comment and close if fixed @frenkiboy @katwre

**Comment by frenkiboy** [comment]
I think I fixed this  :| :| :| - Bora needed smth like this for RCAS
I'll ask Bora when he did the changes, and backtrack using dates
