### ISSUE TITLE
How can I write ScoreMatrixList data to outputfile along with windows

### ISSUE THREAD

**Issue by venuthatikonda** [BIMSBbioinfo/genomation#150]
Hi,

`genomation` is great, I find it quite useful for my work.

However, I was just thinking how to write `scoreMatrix` or `scoreMatrixList` data to output file along with windows as row names.

for example

```
sml = ScoreMatrixList(bam.files, tf.comb, bin.num = 20, type = "bam")
names(sml) = sampleInfo$sampleName[match(names(sml), sampleInfo$fileName)]
sml.scaled = scaleScoreMatrixList(sml)
```

I can access the data with
```
sml$Ctcf@.Data
```
but it is just a matrix, I would like to add corresponding windows as row names.

Thank you.

**Comment by katwre** [comment]
If you'd like to get to row names of a ScoreMatrix object just use the `rownames` function. For example:
`data(cage)
data(promoters)
sm=ScoreMatrix(target=cage,windows=promoters,strand.aware=TRUE,
                                     weight.col="tpm")
your_rownames = rownames(sm)
print(head(your_rownames))`
Regarding ScoreMatrixList ,you can just iterate for each score matrix to get row names of score matrices.

Best,
Kasia

**Comment by al2na** [comment]
you can make a character vector out of coordinates of your windows and assign it to your row names as Kasia indicated.
