### ISSUE TITLE
append a new ScoreMatrix to an existing ScoreMatrixList with c() function

### ISSUE THREAD

**Issue by al2na** [BIMSBbioinfo/genomation#151]
Here is how this works in regular lists, c() function should also work for ScoreMatrixList when adding a new element
 
```
R> LL <- list(a="tom", b="dick")
R> c(LL, c="harry")
$a
[1] "tom"

$b
[1] "dick"

$c
[1] "harry"

R> class(LL)
[1] "list"
R> 
```

**Comment by katwre** [comment]
solved in this pull request https://github.com/BIMSBbioinfo/genomation/pull/154
