### ISSUE TITLE
ScoreMatrixBin: When bin.num = 1 and windows drop chromosomes, wrong index

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/genomation#157]
When bin.num = 1, and windows contain chromosomes not in targets, the
resulting scoreMatrix rownmaes do not correspond to the original rownames of
undropped ranges

**Comment by al2na** [comment]
I don't know where this comes from, are you working on a fix?

**Comment by frenkiboy** [comment]
It should be fixed tomorrow

**Comment by al2na** [comment]
closing this if still an issue, please reopen
