### ISSUE TITLE
how to view  points distribution across the whole genome ?

### ISSUE THREAD

**Issue by zeronot** [BIMSBbioinfo/genomation#164]
HI,
    I have a bed file, I wanna  view  points distribution across the whole genome .
    so how to do that ?

**Comment by katwre** [comment]
Did you have a look at the genomation vignette? https://bioconductor.org/packages/release/bioc/vignettes/genomation/inst/doc/GenomationManual.html Check `ScoreMatrix` and `plotMeta`/`heatMatrix` functions if they could be useful for you.

Kasia
