### ISSUE TITLE
ScorematrixBin returns all 1's when is.noCovNA=T

### ISSUE THREAD

**Issue by IngaPa** [BIMSBbioinfo/genomation#168]
---
title: "ScoreMatrixBinProblem"
author: "IPatarc"
date: "12/1/2017"
output: html_document
---

Problem of getting all 1's on the following toy example and using:
is.noCovNA=T

IMPORTANT!
[PATH_OF_INTEREST] needs to be defined to save test.bw files

```{r}

library(genomation)
library(rtracklayer)
library(S4Vectors)

```

TOY .BIGWIG files LOOK LIKE:
CREATING test.bw files: 

```{r}

test2.bw <- test.bw <- GRanges(c("chr1","chr1","chr1","chr2","chr2","chr2"),
                               IRanges(c(1,5,10,1,5,10),
                                       c(4,9,25,4,9,25)))

test.bw$score <- c(0,1:(length(test.bw)-1))
test2.bw$score <- c(0,1,0,0,0,1)
  
  
seqlengths(test2.bw) <- seqlengths(test.bw) <- c(249250621,243199373)

test2.bw
test.bw


# EXPORTING TOY .BW file
rtracklayer::export.bw(test.bw,"[PATH_OF_INTEREST]/test.bw")
rtracklayer::export.bw(test2.bw,"[PATH_OF_INTEREST]/test2.bw")

```

Whereas toy windows are:

```{r}

regTSS_toy <- GRanges(c(rep("chr1",4),rep("chr2",2)),
                      IRanges(c(1,7,9,15,1,15),c(4,8,14,20,4,20)),
                      c(rep("+",3),rep("-",3)))
regTSS_toy$reg <-  regTSS_toy[c(1,1,3:6)]
regTSS_toy$name2 <- regTSS_toy$name <- paste0("TEST_Reg",
                                              c(1,1,3:length(regTSS_toy)))


regTSS_toy

```

This function uses ScormatrixBin() + bin.num = 1, bin.op = "mean",is.noCovNA = FALSE

```{r}

test2.bw <- "[PATH_OF_INTEREST]/test2.bw"
DataFrame(ScoreMatrixBin(test2.bw,windows=regTSS_toy,is.noCovNA = FALSE,bin.num = 1))  

```

VS

ScoreMatrixBin() + bin.num = 1, bin.op = "mean",is.noCovNA = T

```{r}

DataFrame(ScoreMatrixBin(test2.bw,windows=regTSS_toy,is.noCovNA = TRUE,bin.num = 1))  

```

HOWEVER!

#If weight.col = "score" added to the previous example, results are correct.
# Meaning that is.noCovNA = TRUE works okay with previous example only when 
# weight.col = "score", but is.noCovNA = FALSE works ok in both examples
```{r}
DataFrame(ScoreMatrixBin(test2.bw,windows=regTSS_toy,is.noCovNA = TRUE,bin.num = 1,weight.col = "score"))

```

**Comment by katwre** [comment]
weight.col issue exists in the latest version of genomation (1.10v) and in 1.9.3v from July 5th before Bozena pull requests)
