### ISSUE TITLE
get Annotated data from "AnnotationByFeature" object

### ISSUE THREAD

**Issue by likelet** [BIMSBbioinfo/genomation#171]
I am trying to obtain  annotated data from annotateWithFeatures() function by using getFeatsWithTargetsStats(). But it returns an error `Error in getFeatsWithTargetsStats(cage.annot) : 
  unused argument (cage.annot)`
How can i extract dist.to.TSS data frame from the AnnotationByFeature object?
thanks

my genomation version is 1.6.0 from bioconductor

**Comment by katwre** [comment]
Hi @likelet,
Are you sure that your variable `cage.annot` an AnnotationByFeature object? Can you show me your code?
You can extract dist.to.TSS data using `cage.annot@dist.to.TSS`, I am not sure if it's the prettiest way, but the only one that I can see right now.
And in general I recommend you to use the newest version of genomation (1.10.0).

Kasia

**Comment by likelet** [comment]
hi, Kasia 
thanks for your help, `cage.annot` is just an example. Using "@" is work for me
anyway, I will try the latest version. 
Qi
