### ISSUE TITLE
ScoreMatrixBin() is.noCovNA = T produces all NA's when target is path to .bw file

### ISSUE THREAD

**Issue by IngaPa** [BIMSBbioinfo/genomation#176]
# GOOD EXAMPLE
# following function works well [when .bw file is imported with rtracklayer:import]
ScoreMatrixBin(target = Imported_bigwigfile,
                 windows = Enhancers,
                 is.noCovNA = T,
                 bin.num = 1)

# BAD EXAMPLE
# but IF target argument is path to .bw file then all NA's are produced
(ScoreMatrixBin(target = BW,
                         windows =Enhancers,
                         is.noCovNA = T,
                         bin.num = 1))

Thus,
is.noCovNA = T is not working properly when target is path to .bw file

**Comment by al2na** [comment]
@katwre does @bozmik PR solve this or not ?

**Comment by bozmik** [comment]
I will look into this issue in the evening. @IngaPa could you send me a code with files to reproduce this problem?

**Comment by katwre** [comment]
@IngaPa just told me that it's solved so I close it.
