### ISSUE TITLE
Feature Request: Custom X-Axis

### ISSUE THREAD

**Issue by ATpoint** [BIMSBbioinfo/genomation#187]
It would be desirable to have an additional options for `HeatMatrix()`: An option to add a custom x-axis with full control over the ticks and its labelling. As this cannot be manipulated with basic R graphic commands and I do not understand enough of grid graphics to modify the source myself, something like the traditional `xaxt="n"` and `axis(1, ...)` would be great.

**Comment by katwre** [comment]
Hi @ATpoint ,
What about playing around with `xcoords` to change x-axis tick labels and `cex.axis` to change their size? What would you like modify in x-axis?
Kasia

**Comment by ATpoint** [comment]
Esentially it would be having ticks only at (say you have a 10kb window) -5kb, 0, +5kb. Also the labels are never centered right below the ticks but a bit to the left. Would that be much of an effort?
