### ISSUE TITLE
Error occured using annotateWithFeatures

### ISSUE THREAD

**Issue by frylhc** [BIMSBbioinfo/genomation#202]
Hi everyone,
I am trying to plot a pie chart using annotateWithFeatures, the pie chart indicate the proportion of all methylated sites in each genomic features (CDS,5'UTR,3'UTR,intron,promoter,intergenic). First, I used GenomicRanges package to construct the GRangesList required by annotateWithFeatures. Then, I used annotateWithFeatures to obtain the results, but an error occured. Could you please help me with this? Thanks.

`Error in no.of.OlapFeat[match(hits$annot, names(features))] <- hits$featureHits : 
  NAs are not allowed in subscripted assignments
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': UAContig42, UAContig43
  - in 'y': UAContig12, UAContig18, UAContig19, UAContig20, UAContig21, UAContig25, UAContig26, UAContig29, UAContig40, UAContig45
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).
`

**Comment by al2na** [comment]
it seems there are some contigs in one object that are not present in the
other one and this causes problems with the overlap operation. if you can
make the some objects pair work in functions like
GenomicRanges::findOverlaps or equivalent genomation functions should also
work

**Comment by frylhc** [comment]
Thanks for your suggestion. I'm trying.
Best,

Ruiying Fu
