### ISSUE TITLE
should unique option be applied to all mapped reads when rpm=TRUE

### ISSUE THREAD

**Issue by al2na** [BIMSBbioinfo/genomation#39]
I don't know how easy is to do this. If not easy, it is not so important to have. Could this be done via ScanBam ?

**Comment by katwre** [comment]
I know that you wrote it few years ago, but I can see that the ScanBamParam function can have argument _isDuplicate_ (A logical(1) indicating that un-duplicated (FALSE), duplicated (TRUE), or any (NA) reads should be returned. 'Duplicated' reads may represent PCR or optical duplicates.)
Did you mean something like that?

**Comment by al2na** [comment]
I think that could be for reads mapping to multiple locations

On Monday, 14 December 2015, katwre <notifications@github.com> wrote:

> I know that you wrote it few years ago, but I can see that the
> ScanBamParam function can have argument *isDuplicate* (A logical(1)
> indicating that un-duplicated (FALSE), duplicated (TRUE), or any (NA) reads
> should be returned. 'Duplicated' reads may represent PCR or optical
> duplicates.)
> Did you mean something like that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BIMSBbioinfo/genomation/issues/39#issuecomment-164514691>
> .
>


-- 
Sent from mobile, excuse the brevity

**Comment by al2na** [comment]
I will close this for now, users should filter bam files before getting them into genomation if they don't want PCR duplicates
