### ISSUE TITLE
dealing with paired-end BAM files as fragments

### ISSUE THREAD

**Issue by al2na** [BIMSBbioinfo/genomation#79]
We can add a new parameter to readBam to deal with paired-end BAM files. So paired-reads treated as fragments. 

https://github.com/BIMSBbioinfo/genomation/blob/master/R/scoreMatrix.R#L72

```
library(GenomicAlignments)
library(Rsamtools)  # for the ex1.bam file
ex1_file <- system.file("extdata", "ex1.bam", package="Rsamtools")
galp <- readGAlignmentPairs(ex1_file, use.names=TRUE)
coverage(granges(galp)) # gives the coverage vector

```

**Comment by katwre** [comment]
it can be closed https://github.com/BIMSBbioinfo/genomation/commit/c573bf6859f14b33c7124ec3d9a01c807556efbd
