### ISSUE TITLE
fread/readr into readTableFast

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/genomation#81]
rewrite the readGeneric using fread

**Comment by al2na** [comment]
private(unexported) function readTableFast() should dispatch to fread when the "file" is not compressed or is a remote file (http/ftp in the "file" string)
https://github.com/BIMSBbioinfo/genomation/blob/master/R/readData.R#L3

**Comment by katwre** [comment]
it can be closed https://github.com/BIMSBbioinfo/genomation/commit/84925dc9489c65e08ebaff94d3d564123d959c90
