### ISSUE TITLE
Chromosome name requirement in readTranscriptFeatures()  

### ISSUE THREAD

**Issue by rtraborn** [BIMSBbioinfo/genomation#86]
On line 101 of readAnnotate.R, checkBedValidity() requires that the bed12 file has 'chr' in the first column. While this makes sense for well annotated reference genomes like human, mouse or Drosophila, it prevents usage of genomes with unfinished assemblies (in these cases, the assembly likely has scaffolds rather than chromosomes).

Would it be possible for the bed column 1 chromosome name requirement in checkBedValidity() to be relaxed to fit other use cases? I forked and modified it for my own work so that it accepts my bed12 file, but haven't coded up a more general solution yet. 

Thanks, Taylor

**Comment by al2na** [comment]
Hi Taylor, I will add this as a feature request and we will try to get this on the next update.

Best,
Altuna

**Comment by rtraborn** [comment]
Hi Altuna- thanks so much. I may make a few changes and send you a pull request once I understand this package's codebase a bit better. 
-Taylor

**Comment by al2na** [comment]
I can assign that to you as well. so that we don't work on the same kind of changes. let me know.

**Comment by rtraborn** [comment]
I'm definitely open to that. Can I write something that accepts strings in column 1 with 'chr' or 'scaffold'? It doesn't look like relaxing this will break anything downstream.

**Comment by al2na** [comment]
That should work for now. Very general thing would be to coerce everything
to a string, but I'm not sure if that will breakdown anything downstream.
