### ISSUE TITLE
vignette error: AnnotationHub example

### ISSUE THREAD

**Issue by molecules** [BIMSBbioinfo/genomation#99]
I am getting an error when running the very last example (AnnotationHub). Here is a copy of my interactive session code:

    > ls()
    character(0)
    > library(AnnotationHub)
    > ah = AnnotationHub()
    > cpgi = ah$goldenpath.hg19.database.cpgIslandExt_0.0.1.RData
    Error in .resource_column(x, name) : 
      ‘goldenpath.hg19.database.cpgIslandExt_0.0.1.RData’ is not a resource data column

I even tried running all of the code samples before this and loaded the libraries "genomation" and "GenomicRanges", but got the same errors. 

------
Environment:
This is using Bioconductor version 3.1 (BiocInstaller 1.18.3), R version 3.2.0, running on a brand new CentOS 7.1.1503 virtual machine that I created expressly for the purpose of testing this code.

After using VM Ware Workstation to create the virtual machine using "Easy Install" from a CentOS 7.0 iso, I did the following as root:

    yum install libcurl-devel
    yum install libxml2-devel
    yum install openssl-devel
    yum install epel-release
    yum install R

Then, as a user, I installed genomation as specified in your README file:

    source("http://bioconductor.org/biocLite.R")
    biocLite("genomation")

**Comment by al2na** [comment]
@frenkiboy @katwre can you reproduce this?

**Comment by katwre** [comment]
it works fine on my computers (R version 3.1.3, OS X 10.9.4 (Mavericks) and Ubuntu 14.04.2)

**Comment by molecules** [comment]
With R version 3.2.1, Bioconductor version 3.1 (BiocInstaller 1.18.3), on CentOS release 6.5, I still get the same error:

library(AnnotationHub)
ah = AnnotationHub()
cpgi = ah$goldenpath.hg19.database.cpgIslandExt_0.0.1.RData
Error in .resource_column(x, name) :
  'goldenpath.hg19.database.cpgIslandExt_0.0.1.RData' is not a resource data column

**Comment by molecules** [comment]
Here's another part of the same section of vignette code, that also gives me trouble:

    dnase = paste("goldenpath", "hg19.encodeDCC", "wgEncodeOpenChromDnase", "wgEncodeOpenChromDnase8988tPk", "narrowPeak_0.0.1.RData", sep = ".")
    dnaseP = ah[[dnase]]
    Error in .AnnotationHub_get1(x[idx]) : 'i' must be length 1

**Comment by al2na** [comment]
@katwre can you update R and BioC and try to reproduce the error ?

**Comment by katwre** [comment]
I updated my R (to 3.2.1) and BioC (to 3.1). I've just done pull request with improved code.

**Comment by al2na** [comment]
@molecules this should be fixed now. Can you install and try the the latest version
https://github.com/BIMSBbioinfo/genomation#install-the-latest-version-via-install_github

**Comment by molecules** [comment]
With a fresh install of genomation's dependencies and genomation, the new vignette code ran fine.
Thanks!
________________________________
